[package]
name = "github-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
futures-util = "0.3.28"
reqwest = { version = "0.11.18", features = ["serde_json", "json"] }
serde = { version = "1.0.163", features = ["derive"] }
thiserror = "1.0.40"
